package webserver

import (
	"bufio"
	"context"
	"crypto/tls"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/voidluo/trojan-go/common"
	"github.com/voidluo/trojan-go/internal/certmonitor"
	"github.com/voidluo/trojan-go/log"
	"gopkg.in/yaml.v3"
)

const (
	defaultGatewayListenAddress = "0.0.0.0:443"
	defaultTrojanDataPlane      = "127.0.0.1:14443"
	gatewayHandshakeTimeout     = 10 * time.Second
	gatewayBackendDialTimeout   = 5 * time.Second
)

// GatewayConfig defines the independently deployable TCP/443 edge gateway.
// HTTP routes are handled by ServiceRouter. Non-HTTP traffic is delivered as
// decrypted Trojan bytes to a loopback-only data-plane listener.
// When RelayTable is non-empty, the gateway peeks at TLS ClientHello SNI
// and forwards matching traffic directly to the configured exit address
// without terminating TLS locally.
type GatewayConfig struct {
	ListenAddress  string
	CertPath       string
	KeyPath        string
	AdminAddress   string
	AdminDisabled  bool
	ControlAddress string
	TrojanAddress  string
	AdminPrefix    string
	SubPath        string
	MaxConnections int
	// RelayTable maps TLS SNI domain names to "[host]:port" exit addresses.
	// SNI=key → TCP forward to value. Key uses suffix matching (e.g.
	// "xjp.liteops.top" matches SNI "xjp.liteops.top").
	RelayTable map[string]string
}

// Gateway owns the public TLS listener and keeps all service backends private.
type Gateway struct {
	listener      net.Listener
	tlsConfig     *tls.Config
	serviceRouter *ServiceRouter
	trojanAddress string
	dialer        net.Dialer
	done          chan struct{}
	closeOnce     sync.Once
	workers       sync.WaitGroup
	semaphore     chan struct{}
	// activeConns tracks every accepted connection so that, once the drain
	// deadline expires, Close can forcibly close whatever is still open
	// instead of merely logging the count and returning.
	activeConns map[net.Conn]struct{}
	connMu      sync.Mutex
	// relayTable is the SNI→exit mapping for TCP relay without TLS termination.
	relayTable map[string]string
}

// gatewayFileConfig is intentionally independent from admin-service database
// settings. The edge gateway needs only TLS material, private upstreams, and
// public route prefixes.
type gatewayFileConfig struct {
	SSL struct {
		Cert string `yaml:"cert"`
		Key  string `yaml:"key"`
		// AutoRenew enables in-process certificate monitoring and automatic
		// ACME renewal. When enabled the gateway periodically checks
		// certificate expiry and renews before expiration.
		AutoRenew bool `yaml:"auto_renew"`
		// CertRenewConfig is the path to the acme-renewal.conf file
		// generated by the installer. Required when AutoRenew is true.
		CertRenewConfig string `yaml:"cert_renew_config"`
	} `yaml:"ssl"`
	Gateway struct {
		Listen         string `yaml:"listen"`
		AdminService   string `yaml:"admin_service"`
		AdminDisabled  bool   `yaml:"admin_disabled"`
		ControlService string `yaml:"control_service"`
		TrojanService  string `yaml:"trojan_service"`
		// Relay is a SNI→exit mapping for TCP relay without TLS termination.
		Relay map[string]string `yaml:"relay"`
	} `yaml:"gateway"`
	Routes struct {
		AdminPrefix string `yaml:"admin_prefix"`
		SubPath     string `yaml:"sub_path"`
	} `yaml:"routes"`
}

func loadGatewayConfig(configPath string) (gatewayFileConfig, error) {
	var cfg gatewayFileConfig
	data, err := os.ReadFile(configPath)
	if err != nil {
		return cfg, fmt.Errorf("读取 Gateway 配置失败: %w", err)
	}
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return cfg, fmt.Errorf("解析 Gateway 配置失败: %w", err)
	}
	if cfg.SSL.Cert == "" || cfg.SSL.Key == "" {
		return cfg, fmt.Errorf("Gateway 配置必须包含 ssl.cert 和 ssl.key")
	}
	return cfg, nil
}

func ValidateGatewayConfig(configPath string) error {
	return ValidateGatewayConfigWithPathOverrides(configPath, nil)
}

func ValidateGatewayConfigWithPathOverrides(configPath string, pathOverrides map[string]string) error {
	gatewayFile, err := loadGatewayConfig(configPath)
	if err != nil {
		return err
	}
	if replacement := pathOverrides[filepath.Clean(gatewayFile.SSL.Cert)]; replacement != "" {
		gatewayFile.SSL.Cert = replacement
	}
	if replacement := pathOverrides[filepath.Clean(gatewayFile.SSL.Key)]; replacement != "" {
		gatewayFile.SSL.Key = replacement
	}
	listenAddress := gatewayFile.Gateway.Listen
	if listenAddress == "" {
		listenAddress = defaultGatewayListenAddress
	}
	if _, _, err := net.SplitHostPort(listenAddress); err != nil {
		return fmt.Errorf("无效 Gateway 监听地址 %q: %w", listenAddress, err)
	}
	adminAddress := gatewayFile.Gateway.AdminService
	if !gatewayFile.Gateway.AdminDisabled {
		if adminAddress == "" {
			adminAddress = "127.0.0.1:8081"
		}
		if _, err := loopbackHTTPURL(adminAddress, "admin-service"); err != nil {
			return err
		}
	}
	controlAddress := gatewayFile.Gateway.ControlService
	if controlAddress == "" {
		controlAddress = "127.0.0.1:8082"
	}
	if _, err := loopbackHTTPURL(controlAddress, "control-service"); err != nil {
		return err
	}
	trojanAddress := gatewayFile.Gateway.TrojanService
	if trojanAddress == "" {
		trojanAddress = defaultTrojanDataPlane
	}
	if err := requireLoopbackAddress(trojanAddress, "trojan data-plane"); err != nil {
		return err
	}
	if _, err := tls.LoadX509KeyPair(gatewayFile.SSL.Cert, gatewayFile.SSL.Key); err != nil {
		return fmt.Errorf("加载 Gateway TLS 证书失败: %w", err)
	}
	return nil
}

func RunGatewayService(configPath, listenAddress string) error {
	if err := ValidateGatewayConfig(configPath); err != nil {
		return err
	}
	gatewayFile, err := loadGatewayConfig(configPath)
	if err != nil {
		return err
	}
	if listenAddress == "" {
		listenAddress = gatewayFile.Gateway.Listen
	}
	if listenAddress == "" {
		listenAddress = defaultGatewayListenAddress
	}
	adminAddress := gatewayFile.Gateway.AdminService
	if gatewayFile.Gateway.AdminDisabled {
		adminAddress = ""
	} else if adminAddress == "" {
		adminAddress = "127.0.0.1:8081"
	}
	controlAddress := gatewayFile.Gateway.ControlService
	if controlAddress == "" {
		controlAddress = "127.0.0.1:8082"
	}
	trojanAddress := gatewayFile.Gateway.TrojanService
	if trojanAddress == "" {
		trojanAddress = defaultTrojanDataPlane
	}
	gateway, err := NewGateway(GatewayConfig{
		ListenAddress:  listenAddress,
		CertPath:       gatewayFile.SSL.Cert,
		KeyPath:        gatewayFile.SSL.Key,
		AdminAddress:   adminAddress,
		AdminDisabled:  gatewayFile.Gateway.AdminDisabled,
		ControlAddress: controlAddress,
		TrojanAddress:  trojanAddress,
		AdminPrefix:    gatewayFile.Routes.AdminPrefix,
		SubPath:        gatewayFile.Routes.SubPath,
		RelayTable:     gatewayFile.Gateway.Relay,
	})
	if err != nil {
		return err
	}
	defer gateway.Close()
	go func() {
		<-common.ShutdownContext().Done()
		_ = gateway.Close()
	}()

	// Start certificate auto-renewal monitor if configured.
	if gatewayFile.SSL.AutoRenew && gatewayFile.SSL.CertRenewConfig != "" {
		go startGatewayCertMonitor(gatewayFile.SSL.CertRenewConfig)
		log.Infof("gateway-service: certificate auto-renewal monitor started")
	}

	log.Infof("gateway-service started on %s: admin=%s control=%s trojan=%s", gateway.listener.Addr(), adminAddress, controlAddress, trojanAddress)
	return gateway.Serve()
}

// startGatewayCertMonitor reads the acme-renewal.conf and starts an in-process
// certificate monitor that periodically checks expiry and auto-renews via ACME.
func startGatewayCertMonitor(renewConfigPath string) {
	cfg, err := certmonitor.ReadCertificateRenewalConfig(renewConfigPath)
	if err != nil {
		log.Errorf("gateway cert monitor: cannot read renewal config %s: %v", renewConfigPath, err)
		return
	}

	go func() {
		ticker := time.NewTicker(12 * time.Hour)
		defer ticker.Stop()

		for {
			needsRenewal, inspectErr := certmonitor.CertificateNeedsRenewal(
				cfg.CertificatePath,
				certmonitor.CertificateRenewBefore,
				time.Now(),
			)
			if inspectErr != nil {
				log.Warnf("gateway cert monitor: check failed: %v", inspectErr)
			} else if needsRenewal {
				log.Infof("gateway cert monitor: certificate for %s needs renewal, starting ACME...", cfg.Domain)
				cert, err := certmonitor.ObtainCert(cfg.Domain, cfg.Email, cfg.CAURL)
				if err != nil {
					log.Errorf("gateway cert monitor: ACME renewal failed: %v", err)
				} else if err := certmonitor.WriteCertificateFiles(cfg.CertificatePath, cfg.PrivateKeyPath, cert.Certificate, cert.PrivateKey); err != nil {
					log.Errorf("gateway cert monitor: write cert files failed: %v", err)
				} else {
					log.Infof("gateway cert monitor: renewed certificate for %s successfully", cfg.Domain)
					if output, err := exec.Command("systemctl", "restart", "trojan-go-gateway").CombinedOutput(); err != nil {
						log.Errorf("gateway cert monitor: restart gateway failed: %v\n%s", err, output)
					}
					if cfg.ReloadHysteria {
						_ = exec.Command("systemctl", "restart", "trojan-go-hysteria").Run()
					}
				}
			}

			select {
			case <-common.ShutdownContext().Done():
				return
			case <-ticker.C:
			}
		}
	}()
}

// NewGateway validates all private upstreams before opening the public listener.
func NewGateway(cfg GatewayConfig) (*Gateway, error) {
	if cfg.ListenAddress == "" {
		cfg.ListenAddress = defaultGatewayListenAddress
	}
	if cfg.AdminDisabled {
		cfg.AdminAddress = ""
	} else if cfg.AdminAddress == "" {
		cfg.AdminAddress = "127.0.0.1:8081"
	}
	if cfg.ControlAddress == "" {
		cfg.ControlAddress = "127.0.0.1:8082"
	}
	if cfg.TrojanAddress == "" {
		cfg.TrojanAddress = defaultTrojanDataPlane
	}
	if err := requireLoopbackAddress(cfg.TrojanAddress, "trojan data-plane"); err != nil {
		return nil, err
	}
	cert, err := tls.LoadX509KeyPair(cfg.CertPath, cfg.KeyPath)
	if err != nil {
		return nil, fmt.Errorf("加载 Gateway TLS 证书失败: %w", err)
	}
	router, err := NewServiceRouter(cfg.AdminAddress, cfg.ControlAddress, cfg.AdminPrefix, cfg.SubPath)
	if err != nil {
		return nil, err
	}
	listener, err := net.Listen("tcp", cfg.ListenAddress)
	if err != nil {
		_ = router.Close()
		return nil, fmt.Errorf("监听 Gateway 失败: %w", err)
	}
	maxConn := cfg.MaxConnections
	if maxConn <= 0 {
		maxConn = MaxActiveConnections
	}
	return &Gateway{
		listener:      listener,
		tlsConfig:     &tls.Config{Certificates: []tls.Certificate{cert}, NextProtos: []string{"http/1.1"}, MinVersion: tls.VersionTLS12},
		serviceRouter: router,
		trojanAddress: cfg.TrojanAddress,
		relayTable:    cfg.RelayTable,
		dialer:        net.Dialer{Timeout: gatewayBackendDialTimeout, KeepAlive: 30 * time.Second},
		done:          make(chan struct{}),
		semaphore:     make(chan struct{}, maxConn),
		activeConns:   make(map[net.Conn]struct{}),
	}, nil
}

func requireLoopbackAddress(address, serviceName string) error {
	host, _, err := net.SplitHostPort(address)
	if err != nil {
		return fmt.Errorf("invalid %s address %q: %w", serviceName, address, err)
	}
	ip := net.ParseIP(host)
	if host != "localhost" && (ip == nil || !ip.IsLoopback()) {
		return fmt.Errorf("%s must use a loopback address, got %q", serviceName, address)
	}
	return nil
}

func (g *Gateway) Serve() error {
	for {
		conn, err := g.listener.Accept()
		if err != nil {
			select {
			case <-g.done:
				return nil
			default:
				return fmt.Errorf("Gateway 接收连接失败: %w", err)
			}
		}
		select {
		case g.semaphore <- struct{}{}:
		default:
			_ = conn.Close()
			continue
		}
		g.workers.Add(1)
		g.addConnection(conn)
		go func() {
			defer g.workers.Done()
			defer g.removeConnection(conn)
			defer func() { <-g.semaphore }()
			g.handleConn(conn)
		}()
	}
}

// tryRelayRoute peeks at the TLS ClientHello on rawConn. If the SNI matches a
// key in g.relayTable, the raw TCP stream is forwarded to the configured exit
// address without local TLS termination. Returns (true, nil) if relayed,
// (false, conn) to continue with normal handling using the returned conn
// (which prefixes any bytes already read).
func (g *Gateway) tryRelayRoute(rawConn net.Conn) (bool, net.Conn) {
	_ = rawConn.SetDeadline(time.Now().Add(gatewayHandshakeTimeout))

	// Read TLS record header (5 bytes) to determine the full record length.
	var header [5]byte
	if _, err := io.ReadFull(rawConn, header[:]); err != nil {
		_ = rawConn.Close()
		return true, nil
	}
	if header[0] != 0x16 { // not TLS Handshake
		// Copy out of the stack array so the slice stays valid after return.
		p := &prefixConn{Conn: rawConn, prefix: append([]byte(nil), header[:]...)}
		return false, p
	}
	recordLen := int(header[3])<<8 | int(header[4])
	if recordLen < 38 || recordLen > 16384 { // implausible ClientHello
		_ = rawConn.Close()
		return true, nil
	}

	// Read the exact record body.
	buf := make([]byte, recordLen)
	if _, err := io.ReadFull(rawConn, buf); err != nil {
		_ = rawConn.Close()
		return true, nil
	}
	_ = rawConn.SetDeadline(time.Time{})

	// extractSNI expects the complete TLS record including the 5-byte header,
	// so build fullPayload first and parse from it.
	fullPayload := make([]byte, 0, len(header)+len(buf))
	fullPayload = append(fullPayload, header[:]...)
	fullPayload = append(fullPayload, buf...)

	sni := extractSNI(fullPayload)

	if sni == "" {
		p := &prefixConn{Conn: rawConn, prefix: fullPayload}
		return false, p
	}
	// SNI parsed, continue with relay routing.

	// Suffix-match against relayTable keys.
	var exitAddr string
	for domain, addr := range g.relayTable {
		if strings.HasSuffix(sni, domain) {
			exitAddr = addr
			break
		}
	}
	if exitAddr == "" {
		p := &prefixConn{Conn: rawConn, prefix: fullPayload}
		return false, p
	}

	log.Infof("gateway relay: SNI=%s -> %s", sni, exitAddr)
	exitConn, err := net.DialTimeout("tcp", exitAddr, gatewayBackendDialTimeout)
	if err != nil {
		log.Warnf("gateway relay: dial exit %s: %v", exitAddr, err)
		_ = rawConn.Close()
		return true, nil
	}

	// Forward the full TLS record payload (header + body) to the exit.
	if _, err := exitConn.Write(fullPayload); err != nil {
		_ = exitConn.Close()
		_ = rawConn.Close()
		return true, nil
	}
	relayGatewayConnections(rawConn, exitConn)
	return true, nil
}

// extractSNI parses a TLS ClientHello byte stream and returns the SNI
// hostname, or empty string if not found.
func extractSNI(data []byte) string {
	const recordHeaderLen = 5
	if len(data) < recordHeaderLen || data[0] != 0x16 {
		return ""
	}
	recordLen := int(data[3])<<8 | int(data[4])
	if len(data) < recordHeaderLen+recordLen {
		return ""
	}
	hs := data[recordHeaderLen : recordHeaderLen+recordLen]
	if len(hs) < 1 || hs[0] != 0x01 { // not ClientHello
		return ""
	}
	// Skip: handshake type(1) + length(3) + version(2) + random(32)
	pos := 6 + 32
	if pos >= len(hs) {
		return ""
	}
	// Session ID
	sessLen := int(hs[pos])
	pos += 1 + sessLen
	if pos+2 > len(hs) {
		return ""
	}
	// Cipher suites
	cipherLen := int(hs[pos])<<8 | int(hs[pos+1])
	pos += 2 + cipherLen
	if pos+1 > len(hs) {
		return ""
	}
	// Compression methods
	compLen := int(hs[pos])
	pos += 1 + compLen
	if pos+2 > len(hs) {
		return ""
	}
	// Extensions
	extLen := int(hs[pos])<<8 | int(hs[pos+1])
	pos += 2
	end := pos + extLen
	if end > len(hs) {
		end = len(hs)
	}
	for pos+4 <= end {
		extType := int(hs[pos])<<8 | int(hs[pos+1])
		extDataLen := int(hs[pos+2])<<8 | int(hs[pos+3])
		pos += 4
		if extType == 0 && pos+5 <= end { // SNI (type 0x0000)
			nameLen := int(hs[pos+3])<<8 | int(hs[pos+4])
			if pos+5+nameLen <= end {
				return string(hs[pos+5 : pos+5+nameLen])
			}
			return ""
		}
		pos += extDataLen
	}
	return ""
}

// prefixConn is a net.Conn that prepends a byte slice to the first Read.
type prefixConn struct {
	net.Conn
	prefix []byte
}

func (p *prefixConn) Read(b []byte) (int, error) {
	if len(p.prefix) > 0 {
		n := copy(b, p.prefix)
		p.prefix = p.prefix[n:]
		return n, nil
	}
	return p.Conn.Read(b)
}

func (g *Gateway) handleConn(rawConn net.Conn) {
	// If relayTable is configured, peek at TLS ClientHello SNI before
	// handshake. Matching traffic is forwarded directly to the exit node
	// without local TLS termination.
	if len(g.relayTable) > 0 {
		relayed, conn := g.tryRelayRoute(rawConn)
		if relayed {
			return
		}
		rawConn = conn
	}

	_ = rawConn.SetDeadline(time.Now().Add(gatewayHandshakeTimeout))
	tlsConn := tls.Server(rawConn, g.tlsConfig)
	if err := tlsConn.Handshake(); err != nil {
		_ = rawConn.Close()
		return
	}
	_ = rawConn.SetDeadline(time.Now().Add(gatewayHandshakeTimeout))

	rewindConn := common.NewRewindConn(tlsConn)
	rewindConn.SetBufferSize(16 * 1024)
	request, err := http.ReadRequest(bufio.NewReader(rewindConn))
	rewindConn.Rewind()
	rewindConn.StopBuffering()
	_ = rawConn.SetDeadline(time.Time{})
	if err == nil {
		if g.serviceRouter.Matches(request.URL.Path) {
			g.serviceRouter.ServeConn(rewindConn)
			return
		}
		writeGatewayNotFound(rewindConn)
		return
	}
	g.forwardTrojan(rewindConn)
}

func writeGatewayNotFound(conn net.Conn) {
	body := "Not Found\n"
	_, _ = fmt.Fprintf(conn, "HTTP/1.1 404 Not Found\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: %d\r\nConnection: close\r\n\r\n%s", len(body), body)
	_ = conn.Close()
}

func (g *Gateway) forwardTrojan(client net.Conn) {
	backend, err := g.dialer.DialContext(context.Background(), "tcp", g.trojanAddress)
	if err != nil {
		log.Warnf("gateway-service: Trojan data-plane unavailable: %v", err)
		_ = client.Close()
		return
	}
	if err := writeProxyHeader(backend, client.RemoteAddr(), client.LocalAddr()); err != nil {
		_ = backend.Close()
		_ = client.Close()
		return
	}
	relayGatewayConnections(client, backend)
}

func writeProxyHeader(w io.Writer, source, destination net.Addr) error {
	src, srcOK := source.(*net.TCPAddr)
	dst, dstOK := destination.(*net.TCPAddr)
	if !srcOK || !dstOK || src.IP == nil || dst.IP == nil {
		_, err := io.WriteString(w, "PROXY UNKNOWN\r\n")
		return err
	}
	family := "TCP6"
	if src.IP.To4() != nil && dst.IP.To4() != nil {
		family = "TCP4"
	}
	_, err := fmt.Fprintf(w, "PROXY %s %s %s %d %d\r\n", family, src.IP.String(), dst.IP.String(), src.Port, dst.Port)
	return err
}

func relayGatewayConnections(client, backend net.Conn) {
	defer client.Close()
	defer backend.Close()
	done := make(chan struct{}, 2)
	copyConn := func(dst, src net.Conn) {
		_, _ = io.Copy(dst, src)
		if tcp, ok := dst.(*net.TCPConn); ok {
			_ = tcp.CloseWrite()
		}
		done <- struct{}{}
	}
	go copyConn(backend, client)
	go copyConn(client, backend)
	<-done
}

func (g *Gateway) addConnection(conn net.Conn) {
	g.connMu.Lock()
	g.activeConns[conn] = struct{}{}
	g.connMu.Unlock()
}

func (g *Gateway) removeConnection(conn net.Conn) {
	g.connMu.Lock()
	delete(g.activeConns, conn)
	g.connMu.Unlock()
}

func (g *Gateway) activeConnections() int64 {
	g.connMu.Lock()
	defer g.connMu.Unlock()
	return int64(len(g.activeConns))
}

// forceCloseActiveConns closes every connection still registered. It is called
// once the drain deadline elapses so that in-flight relays are torn down and
// their goroutines can return, rather than being left to linger indefinitely.
func (g *Gateway) forceCloseActiveConns() int {
	g.connMu.Lock()
	conns := make([]net.Conn, 0, len(g.activeConns))
	for conn := range g.activeConns {
		conns = append(conns, conn)
	}
	g.connMu.Unlock()
	for _, conn := range conns {
		_ = conn.Close()
	}
	return len(conns)
}

func (g *Gateway) Close() error {
	g.closeOnce.Do(func() {
		close(g.done)
		_ = g.listener.Close()
	})
	drainDone := make(chan struct{})
	go func() {
		g.workers.Wait()
		close(drainDone)
	}()
	select {
	case <-drainDone:
	case <-time.After(GatewayDrainTimeout):
		// Bounded drain: forcibly close whatever is still open so handler
		// goroutines unblock, then wait for them to finish returning.
		forced := g.forceCloseActiveConns()
		log.Warnf("gateway-service: drain deadline exceeded with %d connections still active, forcing close", forced)
		g.workers.Wait()
	}
	_ = g.serviceRouter.Close()
	return nil
}
